### ISSUE TITLE
Are you still interested to further develop this project?

### ISSUE THREAD

**Issue by deperto** [topfreeworker123/bet356_bot#1]
Can we help 🙌

**Comment by alekdev0** [comment]
Hello
What do you need more function in this repo?
Please let know me.

**Comment by deperto** [comment]
Can you bypass the new authentication method form bet365? 😁

**Comment by alekdev0** [comment]
before, I passed with my tech, but now I am not sure

**Comment by deperto** [comment]
Can you check please if you have time, if possible to bypass the QR code authentication method from phone to pc


Sent from Yahoo Mail for iPhone


On Tuesday, April 4, 2023, 21:00, WH Dev ***@***.***> wrote:




before, I passed with my tech, but now I am not sure

**Comment by alekdev0** [comment]
OKay
let me check
What is your email address?

**Comment by deperto** [comment]
My email is: 
***@***.***


Sent from Yahoo Mail for iPhone


On Tuesday, April 4, 2023, 21:05, WH Dev ***@***.***> wrote:




OKay
let me check
What is your email address?

**Comment by Ashikurxx** [comment]
@WHdev711 i mail you from ashikurxx@gmail.com
